version: '3.3'
services:
  nginx:
    image: nginx
    ports: 
      - 8081:80
      - 4433:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www
  myphp:
    container_name: myphp
    
    image: php:7.4-fpm
    restart: always
    ports:
            - 9000
    volumes:
            - ./src:/var/www
    depends_on:
     - mysql
    
    

  phpMyAdmin:
   container_name: phpMyAdmin
   image: phpmyadmin/phpmyadmin
   restart: always
   depends_on:
    - mysql
   ports:
           - 8082:80   
   environment:
    PMA_HOST: mysql
  mysql:
    image: mariadb:latest
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: cloud_computing
      MYSQL_USER: 123
      MYSQL_PASSWORD: 123
    
 
